<a href="https://colab.research.google.com/github/yakuoku/David-s-Repository/blob/main/Avances_11_01_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([[ 2 , 4 , 5 , 7 ],
            [ 8 , 3, 1, 11],
            [ 14 , 6 , 10 , 12 ],
            [ 9 , 13 , 15 , None ]])
print(a)
print('-------------------------------------------------')
for i in range(len(a)):
  for j in range (len(a[0])):
    if a[i][j]==None:
      print("La posicion del numero indeterminado es",'(',i,',',j,')')
      p=i
      ñ=j
print("Y los numero al rededor son")
for x in range (p-1,p+2):
  for y in range (ñ-1,ñ+2):
    if x<4:
        if x>=0:
          if y<4:
            if y>=0:
             print(a[x][y])
    else:
      pass

[[2 4 5 7]
 [8 3 1 11]
 [14 6 10 12]
 [9 13 15 None]]
-------------------------------------------------
La posicion del numero indeterminado es ( 3 , 3 )
Y los numero al rededor son
10
12
15
None


In [ ]:
a =np.array([[2,    4,  5, 7],
     [10, None,  1, 11],
     [14,   6,  13, 8],
     [ 9,  12,  15, 3]])
print(a)
print('-------------------------------------------------')
for i in range(len(a)):
  for j in range (len(a[0])):
    if a[i][j]==None:
      print("La posicion del numero indeterminado es",'(',i,',',j,')')
      p=i
      ñ=j
print("Y los numero al rededor son")
for x in range (p-1,p+2):
  for y in range (ñ-1,ñ+2):
    if x<4:
        if x>=0:
          if y<4:
            if y>=0:
             print(a[x][y])
    else:
      pass

[[2 4 5 7]
 [10 None 1 11]
 [14 6 13 8]
 [9 12 15 3]]
-------------------------------------------------
La posicion del numero indeterminado es ( 1 , 1 )
Y los numero al rededor son
2
4
5
10
None
1
14
6
13


In [ ]:
a =np.array([[  2,    4,  5, 7],
     [  10,   14,  1, 11],
     [None,    6,  13, 8],
     [   9,   12,  15, 3]])
print(a)
print('-------------------------------------------------')
for i in range(len(a)):
  for j in range (len(a[0])):
    if a[i][j]==None:
      print("La posicion del numero indeterminado es",'(',i,',',j,')')
      p=i
      ñ=j
print("Y los numero al rededor son")
for x in range (p-1,p+2):
  for y in range (ñ-1,ñ+2):
    if x<4:
        if x>=0:
          if y<4:
            if y>=0:
             print(a[x][y])
    else:
      pass

[[2 4 5 7]
 [10 14 1 11]
 [None 6 13 8]
 [9 12 15 3]]
-------------------------------------------------
La posicion del numero indeterminado es ( 2 , 0 )
Y los numero al rededor son
10
14
None
6
9
12


In [ ]:
import numpy as np
a=np.array([[ 2 , 4 , 5 , 7 ],
            [ 8 , 3, 1, 11],
            [ 14 , 6 , 10 , 12 ],
            [ 9 , 13 , 15 , None ]])

def hallar_pos (num):
  y=(num/len(a))-1
  dis=int(y)
  if y-dis!= 0:
    y=int(y+1)
  else:
    y=int(y)

  x=(num-4*y)-1
  return y,x

hallar_pos(8)



(1, 3)