<a href="https://colab.research.google.com/github/yakuoku/David-s-Repository/blob/main/Avances_12_01_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [115]:
import numpy as np

m0=np.array([[ 2 , 4 , 5 , 7 ],
            [ 8 , 3, 1, 11],
            [ 14 , 6 , 10 , 12 ],
            [ 9 , 13 , 15 , None ]]) 

m1=np.array([[  2,    4,  5, 7],
     [  10,   14,  1, 11],
     [None,    6,  13, 8],
     [   9,   12,  15, 3]])

m2=np.array([[2,    4,  5, 7],
     [10, None,  1, 11],
     [14,   6,  13, 8],
     [ 9,  12,  15, 3]])

def busqueda(mat, num):
  for i in range(len(mat)):
    for j in range(len(mat[i])):
      if mat[i][j]==num:
        return (i,j)  


def ordenar_mat(mat):
    print(mat)
    print('------------------')
    step = 0
    for i in range(len(mat)):
      for j in range(len(mat[i])):
        step+=1
        if step==16:  
          break
        else:   
          num = mat[i][j]
          i_n, j_n = busqueda(mat,None)
          mat[i_n][j_n] = num
          mat[i][j]=None
          i_s,j_s=busqueda(mat,step)
          mat[i_s][j_s]=None
          i_n, j_n = busqueda(mat,None)
          mat[i_n][j_n] = step
        print(mat)
        print('------------------')

     


In [116]:
  ordenar_mat(m1)

[[2 4 5 7]
 [10 14 1 11]
 [None 6 13 8]
 [9 12 15 3]]
------------------
[[1 4 5 7]
 [10 14 None 11]
 [2 6 13 8]
 [9 12 15 3]]
------------------
[[1 2 5 7]
 [10 14 4 11]
 [None 6 13 8]
 [9 12 15 3]]
------------------
[[1 2 3 7]
 [10 14 4 11]
 [5 6 13 8]
 [9 12 15 None]]
------------------
[[1 2 3 4]
 [10 14 None 11]
 [5 6 13 8]
 [9 12 15 7]]
------------------
[[1 2 3 4]
 [5 14 10 11]
 [None 6 13 8]
 [9 12 15 7]]
------------------
[[1 2 3 4]
 [5 6 10 11]
 [14 None 13 8]
 [9 12 15 7]]
------------------
[[1 2 3 4]
 [5 6 7 11]
 [14 10 13 8]
 [9 12 15 None]]
------------------
[[1 2 3 4]
 [5 6 7 8]
 [14 10 13 None]
 [9 12 15 11]]
------------------
[[1 2 3 4]
 [5 6 7 8]
 [9 10 13 14]
 [None 12 15 11]]
------------------
[[1 2 3 4]
 [5 6 7 8]
 [9 10 13 14]
 [None 12 15 11]]
------------------
[[1 2 3 4]
 [5 6 7 8]
 [9 10 11 14]
 [13 12 15 None]]
------------------
[[1 2 3 4]
 [5 6 7 8]
 [9 10 11 12]
 [13 None 15 14]]
------------------
[[1 2 3 4]
 [5 6 7 8]
 [9 10 11 12]
 [13 None 15 14